# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "This is the tdl CLI tool used for running the interactive trainings on the https://academy.threedots.tech/"
  homepage "https://academy.threedots.tech/"
  version "0.1.46"

  on_macos do
    on_intel do
      url "https://github.com/ThreeDotsLabs/cli/releases/download/v0.1.46/tdl_Darwin_x86_64"
      sha256 "b58fd7eb003f2406bba03c77bfb0762cb6f94ba8b675ed2c4ae31de4a9cb191d"

      def install
        bin.install "tdl_Darwin_x86_64" => "tdl"
      end
    end
    on_arm do
      url "https://github.com/ThreeDotsLabs/cli/releases/download/v0.1.46/tdl_Darwin_arm64"
      sha256 "f3a6db227eee3c2bfc4d0f64de462e746f848f07ab6e521f487a9ac6fdbcd270"

      def install
        bin.install "tdl_Darwin_arm64" => "tdl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ThreeDotsLabs/cli/releases/download/v0.1.46/tdl_Linux_x86_64"
        sha256 "32544e82be7ed2a521d3fb4ff283a1c1a7d8cb2179b02caa0fc8bca1f8ae4507"

        def install
          bin.install "tdl_Linux_x86_64" => "tdl"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/ThreeDotsLabs/cli/releases/download/v0.1.46/tdl_Linux_arm"
        sha256 "be41221dc82bb40785674bef1645e5318811da03de64263b7ee133280c7ffc34"

        def install
          bin.install "tdl_Linux_arm" => "tdl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ThreeDotsLabs/cli/releases/download/v0.1.46/tdl_Linux_arm64"
        sha256 "f5b639a2ba53af181d1661a2d6667b56859d3a8afd4f6cfae22f37c97b0b95ba"

        def install
          bin.install "tdl_Linux_arm64" => "tdl"
        end
      end
    end
  end

  head "https://github.com/ThreeDotsLabs/cli.git"
end
