# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tdl < Formula
  desc "This is the tdl CLI tool used for running the interactive trainings on the https://academy.threedots.tech/"
  homepage "https://academy.threedots.tech/"
  version "0.1.72"

  on_macos do
    on_intel do
      url "https://github.com/ThreeDotsLabs/cli/releases/download/v0.1.72/tdl_Darwin_x86_64"
      sha256 "fe020af2623b954e14c8c633c6efa944f65342b577ff53ee4b7214fb8d981a3c"

      def install
        bin.install "tdl_Darwin_x86_64" => "tdl"
      end
    end
    on_arm do
      url "https://github.com/ThreeDotsLabs/cli/releases/download/v0.1.72/tdl_Darwin_arm64"
      sha256 "7df528eb7ee7147cfba28a905bbef8b9f2b04cd3459b9e662498a580f9da44f8"

      def install
        bin.install "tdl_Darwin_arm64" => "tdl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ThreeDotsLabs/cli/releases/download/v0.1.72/tdl_Linux_x86_64"
        sha256 "37ef7125fd6ed491f0e0008cacd3a7533a7076913e6bc070d968be61c03cea18"

        def install
          bin.install "tdl_Linux_x86_64" => "tdl"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/ThreeDotsLabs/cli/releases/download/v0.1.72/tdl_Linux_arm"
        sha256 "87e96590651790460f6e495b83701f2f2eded149328b7ce6169df5db19e7bf50"

        def install
          bin.install "tdl_Linux_arm" => "tdl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ThreeDotsLabs/cli/releases/download/v0.1.72/tdl_Linux_arm64"
        sha256 "c1e725ee7d9ad0acd4fdc4fa7d575e3e21cadf6aeeed4d6319a9791e2d647651"

        def install
          bin.install "tdl_Linux_arm64" => "tdl"
        end
      end
    end
  end

  head "https://github.com/ThreeDotsLabs/cli.git"
end
