# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tdl < Formula
  desc "This is the tdl CLI tool used for running the interactive trainings on the https://academy.threedots.tech/"
  homepage "https://academy.threedots.tech/"
  version "0.1.57"

  on_macos do
    on_intel do
      url "https://github.com/ThreeDotsLabs/cli/releases/download/v0.1.57/tdl_Darwin_x86_64"
      sha256 "526ad7baa626df2168547fcbb76001ffa267ab874e81340e56f75d7db732f02f"

      def install
        bin.install "tdl_Darwin_x86_64" => "tdl"
      end
    end
    on_arm do
      url "https://github.com/ThreeDotsLabs/cli/releases/download/v0.1.57/tdl_Darwin_arm64"
      sha256 "63dfb446bed6349fb3d1a327d6d00cfa52372a8ffc65fc5a68f41bc18cd6dbc7"

      def install
        bin.install "tdl_Darwin_arm64" => "tdl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ThreeDotsLabs/cli/releases/download/v0.1.57/tdl_Linux_x86_64"
        sha256 "7a2d2eb1808276243aeb002050337c0e3a5c3d274b007dea5f8b774dc3b03a48"

        def install
          bin.install "tdl_Linux_x86_64" => "tdl"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/ThreeDotsLabs/cli/releases/download/v0.1.57/tdl_Linux_arm"
        sha256 "29ed221542ccfc08c329e6e7a42db35c01f52fe1e2eaa2a231eb162cb0c647a6"

        def install
          bin.install "tdl_Linux_arm" => "tdl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ThreeDotsLabs/cli/releases/download/v0.1.57/tdl_Linux_arm64"
        sha256 "85463013cdec9e534dfdba64722c010ffb51069736f986f4170ea41b88e9c333"

        def install
          bin.install "tdl_Linux_arm64" => "tdl"
        end
      end
    end
  end

  head "https://github.com/ThreeDotsLabs/cli.git"
end
