# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tdl < Formula
  desc "This is the tdl CLI tool used for running the interactive trainings on the https://academy.threedots.tech/"
  homepage "https://academy.threedots.tech/"
  version "0.1.49"

  on_macos do
    on_intel do
      url "https://github.com/ThreeDotsLabs/cli/releases/download/v0.1.49/tdl_Darwin_x86_64"
      sha256 "f642d1915abb16903f6b43fb85b1f717b41d6ca9d0d1caf70049f2798d74d121"

      def install
        bin.install "tdl_Darwin_x86_64" => "tdl"
      end
    end
    on_arm do
      url "https://github.com/ThreeDotsLabs/cli/releases/download/v0.1.49/tdl_Darwin_arm64"
      sha256 "d8adb511bde504390f7e020fc9b27258c45a93e6cfd8077549d68efbd6ed285d"

      def install
        bin.install "tdl_Darwin_arm64" => "tdl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ThreeDotsLabs/cli/releases/download/v0.1.49/tdl_Linux_x86_64"
        sha256 "3bc6e4aeb48bd75e52aaf42af5d68a8ec82021c1f9d8e9fca5f906a6b76c6373"

        def install
          bin.install "tdl_Linux_x86_64" => "tdl"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/ThreeDotsLabs/cli/releases/download/v0.1.49/tdl_Linux_arm"
        sha256 "059e9deff389c92ab96a38be9eb336653d6fb3cdf505c48251bd7b3b3583f0db"

        def install
          bin.install "tdl_Linux_arm" => "tdl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ThreeDotsLabs/cli/releases/download/v0.1.49/tdl_Linux_arm64"
        sha256 "670ac84c9a7c339e447a740928fc4dff2edde14bcd867d9a2139722fb5c28669"

        def install
          bin.install "tdl_Linux_arm64" => "tdl"
        end
      end
    end
  end

  head "https://github.com/ThreeDotsLabs/cli.git"
end
